---
# Source: hello-world/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
# Source: hello-world/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  annotations:
    version: 0.0.1-30
spec:
  strategy: 
    type: Recreate      
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world      
      annotations:
        version: 0.0.1-30
    spec:
      containers:
      - name: hello-world
        image: ghcr.io/microsoft/kalypso-app-src/hello-world:0.0.1-30
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: CLUSTER_NAME
          valueFrom:
              configMapKeyRef:
                name: platform-config
                key: CLUSTER_NAME
        - name: REGION
          valueFrom:
              configMapKeyRef:
                name: platform-config
                key: REGION
        - name: ENVIRONMENT
          valueFrom:
              configMapKeyRef:
                name: platform-config
                key: ENVIRONMENT
        - name: DATABASE_URL
          valueFrom:
              configMapKeyRef:
                name: platform-config
                key: DATABASE_URL
